-------------------- Log Start | Thu Oct 24 22:27:10 2024 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################
2024-10-24 18:27:10,405 [confighelper.py:read_file()] - Configuration File '/home/daniel/printer_data/config/moonraker.conf' parsed, total size: 1635 B
2024-10-24 18:27:10,405 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################
2024-10-24 18:27:11,765 [server.py:load_component()] - Component (secrets) loaded
2024-10-24 18:27:11,771 [server.py:load_component()] - Component (template) loaded
2024-10-24 18:27:11,776 [server.py:load_component()] - Component (klippy_connection) loaded
2024-10-24 18:27:16,546 [server.py:load_component()] - Component (application) loaded
2024-10-24 18:27:16,797 [server.py:load_component()] - Component (websockets) loaded
2024-10-24 18:27:17,461 [server.py:load_component()] - Component (dbus_manager) loaded
2024-10-24 18:27:17,757 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 4
2024-10-24 18:27:18,004 [server.py:load_component()] - Component (database) loaded
2024-10-24 18:27:18,228 [file_manager.py:__init__()] - Using File System Observer: inotify
2024-10-24 18:27:18,634 [server.py:load_component()] - Component (file_manager) loaded
2024-10-24 18:27:18,763 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
.*\.lan
.*\.local
.*://localhost
.*://localhost:.*
.*://my\.mainsail\.xyz
.*://app\.fluidd\.xyz
2024-10-24 18:27:18,765 [server.py:load_component()] - Component (authorization) loaded
2024-10-24 18:27:18,768 [server.py:load_component()] - Component (klippy_apis) loaded
2024-10-24 18:27:19,614 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115828
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2024-10-24 18:27:19,615 [server.py:load_component()] - Component (shell_command) loaded
2024-10-24 18:27:19,616 [machine.py:__init__()] - Using System Provider: systemd_dbus
2024-10-24 18:27:19,620 [server.py:add_log_rollover_item()] - Module libcamera unavailble, import failed
2024-10-24 18:27:19,620 [server.py:load_component()] - Component (machine) loaded
2024-10-24 18:27:19,623 [server.py:load_component()] - Component (data_store) loaded
2024-10-24 18:27:19,624 [proc_stats.py:__init__()] - Unable to find 'vcgencmd', throttle checking disabled
2024-10-24 18:27:19,625 [server.py:load_component()] - Component (proc_stats) loaded
2024-10-24 18:27:19,626 [server.py:load_component()] - Component (job_state) loaded
2024-10-24 18:27:19,629 [server.py:load_component()] - Component (job_queue) loaded
2024-10-24 18:27:19,676 [server.py:load_component()] - Component (http_client) loaded
2024-10-24 18:27:19,679 [server.py:load_component()] - Component (announcements) loaded
2024-10-24 18:27:19,681 [server.py:load_component()] - Component (webcam) loaded
2024-10-24 18:27:19,682 [server.py:load_component()] - Component (extensions) loaded
2024-10-24 18:27:19,701 [server.py:load_component()] - Component (history) loaded
2024-10-24 18:27:19,721 [power.py:__init__()] - Power component loading devices: ['power printer_plug']
2024-10-24 18:27:19,723 [server.py:load_component()] - Component (power) loaded
2024-10-24 18:27:19,741 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/daniel/moonraker-env
2024-10-24 18:27:19,742 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/daniel/klippy-env
2024-10-24 18:27:19,800 [server.py:load_component()] - Component (update_manager) loaded
2024-10-24 18:27:19,804 [server.py:load_component()] - Component (octoprint_compat) loaded
2024-10-24 18:27:19,805 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2024-10-24 18:27:19,811 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2024-10-24 18:27:19,882 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2024-10-24 18:27:19,882 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2024-10-24 18:27:19,882 [machine.py:validation_init()] - Installation version in database up to date
2024-10-24 18:27:20,151 [machine.py:check_virt_status()] - No Virtualization Detected
2024-10-24 18:27:20,367 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice', '-.mount']
**After=['network-online.target', 'systemd-journald.socket', 'sysinit.target', 'system.slice', '-.mount', 'basic.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel
2024-10-24 18:27:20,368 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2024-10-24 18:27:20,368 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2024-10-24 18:27:20,369 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2024-10-24 18:27:20,369 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2024-10-24 18:27:20,370 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['network-online.target', 'sysinit.target', '-.mount', 'system.slice', 'basic.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2024-10-24 18:27:20,370 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2024-10-24 18:27:20,372 [server.py:_initialize_component()] - Performing Component Post Init: [power]
2024-10-24 18:27:20,372 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2024-10-24 18:27:20,374 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
2024-10-24 18:27:21,021 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2024-10-24 18:27:21,151 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/daniel/printer_data/comms/moonraker.sock'
2024-10-24 18:27:21,151 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: basement
2024-10-24 18:27:21,152 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2024-10-24 18:27:21,404 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-10-24 18:27:21,424 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['basic.target', 'network-online.target', 'sysinit.target', '-.mount', 'system.slice', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2024-10-24 18:27:21,676 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-111-g4f00f219
2024-10-24 18:27:22,391 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 18:27:24,412 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 18:27:34,001 [base_deploy.py:log_info()] - PackageKit: Detected 91 package updates:
alsa-ucm-conf
apport
apport-gtk
apport-kde
apt
apt-utils
base-files
coreutils
dpkg
dpkg-dev
e2fsprogs
firmware-sof-signed
gir1.2-mutter-10
gjs
gnome-remote-desktop
google-chrome-stable
language-pack-en
language-pack-en-base
libapt-pkg6.0
libcom-err2
libdpkg-perl
libext2fs2
libgjs0g
libgpgme11
libgpgmepp6
libldap-2.5-0
libldap-common
libmm-glib0
libmutter-10-0
libpcap0.8
libpulse-mainloop-glib0
libpulse0
libpulsedsp
libpython3-dev
libpython3-stdlib
libsmbclient
libss2
libwbclient0
linux-firmware
logsave
modemmanager
mutter
mutter-common
openvpn
plasma-distro-release-notifier
pulseaudio
pulseaudio-module-bluetooth
pulseaudio-module-gsettings
pulseaudio-utils
python-apt-common
python3
python3-apport
python3-apt
python3-dev
python3-distupgrade
python3-gpg
python3-minimal
python3-problem-report
python3-samba
python3-update-manager
samba-common
samba-common-bin
samba-dsdb-modules
samba-libs
shim-signed
smbclient
tcpdump
tracker-extract
tracker-miner-fs
tzdata
ubuntu-advantage-tools
ubuntu-drivers-common
ubuntu-minimal
ubuntu-pro-client-l10n
ubuntu-release-upgrader-core
ubuntu-release-upgrader-gtk
ubuntu-release-upgrader-qt
ubuntu-standard
update-manager
update-manager-core
update-notifier
update-notifier-common
xdg-desktop-portal
xdg-desktop-portal-gnome
xserver-common
xserver-xephyr
xserver-xorg-core
xserver-xorg-legacy
ubuntu-pro-client
libnetplan0
netplan.io
2024-10-24 18:27:34,669 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker status --porcelain -b) successfully finished
2024-10-24 18:27:34,675 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker branch --list --no-color) successfully finished
2024-10-24 18:27:34,679 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker remote get-url origin) successfully finished
2024-10-24 18:27:35,534 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:35,537 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:36,038 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:36,039 [git_deploy.py:refresh_repo_state()] - Git Repo moonraker: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:36,039 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:36,163 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper status --porcelain -b) successfully finished
2024-10-24 18:27:36,170 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper branch --list --no-color) successfully finished
2024-10-24 18:27:36,175 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper remote get-url origin) successfully finished
2024-10-24 18:27:36,186 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:36,187 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:36,689 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:36,689 [git_deploy.py:refresh_repo_state()] - Git Repo klipper: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:36,689 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:37,279 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config status --porcelain -b) successfully finished
2024-10-24 18:27:37,284 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config branch --list --no-color) successfully finished
2024-10-24 18:27:37,289 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config remote get-url origin) successfully finished
2024-10-24 18:27:37,300 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:37,302 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:37,803 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:37,803 [git_deploy.py:refresh_repo_state()] - Git Repo mainsail-config: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:37,803 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:38,813 [base_deploy.py:log_info()] - Web Client mainsail: Github Request Error - [Errno -3] Temporary failure in name resolution
2024-10-24 18:27:38,814 [base_deploy.py:log_info()] - Web Client mainsail: Detected
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/daniel/mainsail
Local Version: v2.10.0
Remote Version: v2.10.0
Valid: True
Fallback Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.10.0/mainsail.zip
Download Size: 2081565
Content Type: application/zip
Rollback Version: v2.10.0
Rollback Repo: mainsail-crew/mainsail
2024-10-24 18:27:39,469 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging status --porcelain -b) successfully finished
2024-10-24 18:27:39,474 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging branch --list --no-color) successfully finished
2024-10-24 18:27:39,479 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging remote get-url origin) successfully finished
2024-10-24 18:27:39,489 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:39,491 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:39,993 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:39,993 [git_deploy.py:refresh_repo_state()] - Git Repo Klipper-Adaptive-Meshing-Purging: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:39,993 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:40,353 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup status --porcelain -b) successfully finished
2024-10-24 18:27:40,358 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup branch --list --no-color) successfully finished
2024-10-24 18:27:40,363 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup remote get-url origin) successfully finished
2024-10-24 18:27:40,373 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:40,375 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:40,876 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:40,876 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:40,876 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:41,253 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest status --porcelain -b) successfully finished
2024-10-24 18:27:41,258 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest branch --list --no-color) successfully finished
2024-10-24 18:27:41,262 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest remote get-url origin) successfully finished
2024-10-24 18:27:41,273 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest fetch origin --prune --progress) exited with return code 128
2024-10-24 18:27:41,275 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2024-10-24 18:27:41,776 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2024-10-24 18:27:41,776 [git_deploy.py:refresh_repo_state()] - Git Repo crowsnest: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:27:41,776 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2024-10-24 18:28:46,100 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-10-24 18:28:46,101 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-10-24 18:28:46,104 [klippy_connection.py:_check_ready()] - 
mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2024-10-24 18:57:22,398 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 18:57:24,421 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 19:27:22,401 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 19:27:24,424 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 19:57:22,402 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 19:57:24,424 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 20:27:22,402 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 20:27:24,424 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 20:57:22,404 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 20:57:24,426 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 21:27:22,406 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 21:27:24,427 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 21:57:22,405 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 21:57:24,428 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 22:27:22,407 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 22:27:24,428 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 22:57:22,408 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 22:57:24,431 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 23:27:22,410 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 23:27:24,431 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2024-10-24 23:57:22,411 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2024-10-24 23:57:24,436 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
