-------------------- Log Start | Mon Jun  9 04:20:43 2025 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 5

System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115808
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
Module libcamera unavailble, import failed

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['network-online.target', 'sysinit.target', 'system.slice', '-.mount']
**After=['system.slice', 'basic.target', 'systemd-journald.socket', '-.mount', 'network-online.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['systemd-journald.socket', 'system.slice', '-.mount', 'network-online.target', 'basic.target', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
Git Repo moonraker: No warnings detected
Git Repo klipper: No warnings detected
Git Repo mainsail-config: No warnings detected
Git Repo Klipper-Adaptive-Meshing-Purging: No warnings detected
Git Repo klipper-backup: No warnings detected
Git Repo crowsnest: No warnings detected
Klipper Version: v0.12.0-111-g4f00f219
2025-06-09 00:20:43,778 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.165
2025-06-09 02:11:00,239 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.40
2025-06-09 02:11:00,241 [application.py:prepare()] - Upload Request Received from 192.168.0.40
Content-Type: multipart/form-data; boundary=------------------------11e293339d4ef4c0
2025-06-09 02:11:00,258 [application.py:post()] - Processing Uploaded File: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced.stl_1h51m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-06-09 02:11:00,368 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is enabled

2025-06-09 02:11:00,380 [shell_command.py:pipe_data_received()] - INFO:prepropress_cancellation:Shapely not found, complex hulls disabled

2025-06-09 02:11:00,383 [shell_command.py:pipe_data_received()] - INFO:metadata:Performing Object Processing on file: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced.stl_1h51m_0.20mm_205C_PLA_ENDER3S1.gcode, sliced by PrusaSlicer

2025-06-09 02:11:00,617 [shell_command.py:_check_proc_success()] - Command (/home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/components/file_manager/metadata.py -p /home/daniel/printer_data/gcodes -f "Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced.stl_1h51m_0.20mm_205C_PLA_ENDER3S1.gcode" --check-objects) successfully finished
2025-06-09 02:11:00,627 [application.py:log_request()] - 201 POST /server/files/upload (192.168.0.40) [_TRUSTED_USER_] 385.63ms
2025-06-09 02:11:00,635 [job_state.py:_status_update()] - Job Started: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced.stl_1h51m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-06-09 02:11:01,809 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.165
2025-06-09 02:11:01,958 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-06-09 03:15:43,806 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.40
2025-06-09 03:15:43,806 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.165
2025-06-09 03:15:43,806 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-06-09 13:12:23,753 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.40
2025-06-09 13:12:23,755 [application.py:prepare()] - Upload Request Received from 192.168.0.40
Content-Type: multipart/form-data; boundary=------------------------8303b23e68ce2555
2025-06-09 13:12:23,766 [application.py:post()] - Processing Uploaded File: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced_fixed.stl_1h57m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-06-09 13:12:23,928 [shell_command.py:pipe_data_received()] - INFO:metadata:Object Processing is enabled

2025-06-09 13:12:23,942 [shell_command.py:pipe_data_received()] - INFO:prepropress_cancellation:Shapely not found, complex hulls disabled

2025-06-09 13:12:23,944 [shell_command.py:pipe_data_received()] - INFO:metadata:Performing Object Processing on file: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced_fixed.stl_1h57m_0.20mm_205C_PLA_ENDER3S1.gcode, sliced by PrusaSlicer

2025-06-09 13:12:24,265 [shell_command.py:_check_proc_success()] - Command (/home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/components/file_manager/metadata.py -p /home/daniel/printer_data/gcodes -f "Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced_fixed.stl_1h57m_0.20mm_205C_PLA_ENDER3S1.gcode" --check-objects) successfully finished
2025-06-09 13:12:24,286 [application.py:log_request()] - 201 POST /server/files/upload (192.168.0.40) [_TRUSTED_USER_] 531.75ms
2025-06-09 13:12:24,391 [job_state.py:_status_update()] - Job Started: Slim_enclosure_for_Heltec_Wireless_Tracker__M5Stack_CardKB_Lid_Reinforced_fixed.stl_1h57m_0.20mm_205C_PLA_ENDER3S1.gcode
2025-06-09 13:12:25,439 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.165
2025-06-09 13:12:25,490 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-06-09 14:15:43,927 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.40
2025-06-09 14:15:43,927 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.165
2025-06-09 14:15:43,928 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-06-09 15:16:54,225 [klippy_connection.py:_process_status_update()] - Klippy has shutdown
2025-06-09 15:16:54,232 [proc_stats.py:_handle_shutdown()] - 
Moonraker System Usage Statistics:
System Time: 1749496584.877562, Usage: 0.85%, Memory: 54728 kB
System Time: 1749496585.877921, Usage: 0.87%, Memory: 54728 kB
System Time: 1749496586.879399, Usage: 0.78%, Memory: 54728 kB
System Time: 1749496587.879845, Usage: 0.7%, Memory: 54728 kB
System Time: 1749496588.880767, Usage: 0.67%, Memory: 54728 kB
System Time: 1749496589.881693, Usage: 0.7%, Memory: 54728 kB
System Time: 1749496590.882889, Usage: 0.84%, Memory: 54728 kB
System Time: 1749496591.883886, Usage: 0.78%, Memory: 54728 kB
System Time: 1749496592.884884, Usage: 0.71%, Memory: 54728 kB
System Time: 1749496593.888160, Usage: 0.61%, Memory: 54728 kB
System Time: 1749496594.887778, Usage: 0.77%, Memory: 54728 kB
System Time: 1749496595.889624, Usage: 0.74%, Memory: 54728 kB
System Time: 1749496596.889871, Usage: 0.9%, Memory: 54728 kB
System Time: 1749496597.892952, Usage: 0.72%, Memory: 54728 kB
System Time: 1749496598.892589, Usage: 0.73%, Memory: 54728 kB
System Time: 1749496599.894424, Usage: 0.81%, Memory: 54728 kB
System Time: 1749496600.894038, Usage: 0.79%, Memory: 54728 kB
System Time: 1749496601.895917, Usage: 0.59%, Memory: 54728 kB
System Time: 1749496602.895815, Usage: 0.65%, Memory: 54728 kB
System Time: 1749496603.897677, Usage: 0.66%, Memory: 54728 kB
System Time: 1749496604.898561, Usage: 0.7%, Memory: 54728 kB
System Time: 1749496605.899606, Usage: 0.72%, Memory: 54728 kB
System Time: 1749496606.899788, Usage: 0.96%, Memory: 54728 kB
System Time: 1749496607.901561, Usage: 0.83%, Memory: 54728 kB
System Time: 1749496608.901529, Usage: 0.8%, Memory: 54728 kB
System Time: 1749496609.901515, Usage: 0.94%, Memory: 54728 kB
System Time: 1749496610.902428, Usage: 1.13%, Memory: 54728 kB
System Time: 1749496611.902388, Usage: 0.74%, Memory: 54728 kB
System Time: 1749496612.903394, Usage: 0.99%, Memory: 54728 kB
System Time: 1749496613.904383, Usage: 0.62%, Memory: 54728 kB
CPU Temperature: 44.0
2025-06-09 15:19:27,111 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2025-06-09 15:19:27,217 [websockets.py:on_close()] - Websocket Closed: ID: 139802733852944 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 2.93
2025-06-09 15:19:27,233 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-06-09 15:19:27,233 [websockets.py:write_to_socket()] - Websocket closed while writing: 139802771879632
2025-06-09 15:19:27,236 [websockets.py:on_close()] - Websocket Closed: ID: 139802771879632 Close Code: None, Close Reason: None, Pong Time Elapsed: 8.17
2025-06-09 15:19:28,338 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 17
overflow_pages: 0
entries: 55
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 44
overflow_pages: 0
entries: 105
mainsail:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 9
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 8
update_manager:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 3
overflow_pages: 11
entries: 8
webcams:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
2025-06-09 15:19:30,850 [server.py:main()] - Server Shutdown
-------------------- Log Start | Mon Jun  9 20:52:29 2025 --------------------
data_path: /home/daniel/printer_data
is_default_data_path: False
config_file: /home/daniel/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: b58008b63adb40a8a31f7dfdb480fcc5
unix_socket_path: /home/daniel/printer_data/comms/moonraker.sock
software_version: v0.8.0-311-g65a8271
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/daniel/printer_data/logs/moonraker.log
python_version: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]
launch_args: /home/daniel/moonraker-env/bin/python /home/daniel/moonraker/moonraker/moonraker.py -d /home/daniel/printer_data
msgspec_enabled: False
uvloop_enabled: False
2025-06-09 16:52:29,732 [confighelper.py:read_file()] - Configuration File '/home/daniel/printer_data/config/moonraker.conf' parsed, total size: 1635 B
2025-06-09 16:52:29,732 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/daniel/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[file_manager]
enable_object_processing = True

[power printer_plug]
type = tplink_smartplug
address = 192.168.0.83

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager Klipper-Adaptive-Meshing-Purging]
type = git_repo
channel = dev
path = ~/Klipper-Adaptive-Meshing-Purging
origin = https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services = klipper
primary_branch = main

[update_manager klipper-backup]
type = git_repo
path = ~/klipper-backup
origin = https://github.com/Staubgeborener/klipper-backup.git
managed_services = moonraker
primary_branch = main

[update_manager crowsnest]
type = git_repo
path = ~/crowsnest
origin = https://github.com/mainsail-crew/crowsnest.git
managed_services = crowsnest
install_script = tools/pkglist.sh

#################################################################
All Configuration Files:
/home/daniel/printer_data/config/moonraker.conf
#################################################################
2025-06-09 16:52:30,516 [server.py:load_component()] - Component (secrets) loaded
2025-06-09 16:52:30,533 [server.py:load_component()] - Component (template) loaded
2025-06-09 16:52:30,536 [server.py:load_component()] - Component (klippy_connection) loaded
2025-06-09 16:52:35,311 [server.py:load_component()] - Component (application) loaded
2025-06-09 16:52:36,137 [server.py:load_component()] - Component (websockets) loaded
2025-06-09 16:52:36,583 [server.py:load_component()] - Component (dbus_manager) loaded
2025-06-09 16:52:37,195 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 5
2025-06-09 16:52:37,479 [server.py:load_component()] - Component (database) loaded
2025-06-09 16:52:37,701 [file_manager.py:__init__()] - Using File System Observer: inotify
2025-06-09 16:52:37,821 [server.py:load_component()] - Component (file_manager) loaded
2025-06-09 16:52:38,022 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.0.0/16
fe80::/10
::1/128
CORS Domains:
.*\.lan
.*\.local
.*://localhost
.*://localhost:.*
.*://my\.mainsail\.xyz
.*://app\.fluidd\.xyz
2025-06-09 16:52:38,023 [server.py:load_component()] - Component (authorization) loaded
2025-06-09 16:52:38,025 [server.py:load_component()] - Component (klippy_apis) loaded
2025-06-09 16:52:39,325 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 10, 12, 'final', 0)
  version_string: 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: x86_64
  cpu_desc: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
  serial_number: 
  hardware_desc: 
  model: 
  total_memory: 12115816
  memory_units: kB

***sd_info***

***distribution***
  name: Ubuntu 22.04.4 LTS
  id: ubuntu
  version: 22.04
  version_parts: {'major': '22', 'minor': '04', 'build_number': ''}
  like: debian
  codename: jammy
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2025-06-09 16:52:39,328 [server.py:load_component()] - Component (shell_command) loaded
2025-06-09 16:52:39,328 [machine.py:__init__()] - Using System Provider: systemd_dbus
2025-06-09 16:52:39,333 [server.py:add_log_rollover_item()] - Module libcamera unavailble, import failed
2025-06-09 16:52:39,333 [server.py:load_component()] - Component (machine) loaded
2025-06-09 16:52:39,336 [server.py:load_component()] - Component (data_store) loaded
2025-06-09 16:52:39,337 [proc_stats.py:__init__()] - Unable to find 'vcgencmd', throttle checking disabled
2025-06-09 16:52:39,337 [server.py:load_component()] - Component (proc_stats) loaded
2025-06-09 16:52:39,338 [server.py:load_component()] - Component (job_state) loaded
2025-06-09 16:52:39,340 [server.py:load_component()] - Component (job_queue) loaded
2025-06-09 16:52:39,570 [server.py:load_component()] - Component (http_client) loaded
2025-06-09 16:52:39,604 [server.py:load_component()] - Component (announcements) loaded
2025-06-09 16:52:39,606 [server.py:load_component()] - Component (webcam) loaded
2025-06-09 16:52:39,607 [server.py:load_component()] - Component (extensions) loaded
2025-06-09 16:52:39,662 [power.py:__init__()] - Power component loading devices: ['power printer_plug']
2025-06-09 16:52:39,665 [server.py:load_component()] - Component (power) loaded
2025-06-09 16:52:39,763 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/daniel/moonraker-env
2025-06-09 16:52:39,765 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/daniel/klippy-env
2025-06-09 16:52:39,798 [server.py:load_component()] - Component (update_manager) loaded
2025-06-09 16:52:39,802 [server.py:load_component()] - Component (octoprint_compat) loaded
2025-06-09 16:52:39,804 [server.py:load_component()] - Component (history) loaded
2025-06-09 16:52:39,804 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2025-06-09 16:52:39,810 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2025-06-09 16:52:40,291 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2025-06-09 16:52:40,291 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2025-06-09 16:52:40,292 [machine.py:validation_init()] - Installation version in database up to date
2025-06-09 16:52:40,383 [machine.py:check_virt_status()] - No Virtualization Detected
2025-06-09 16:52:40,516 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'network-online.target', 'system.slice', '-.mount']
**After=['system.slice', 'systemd-journald.socket', '-.mount', 'network-online.target', 'basic.target', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/daniel/printer_data/systemd/moonraker.env
**ExecStart=/home/daniel/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/daniel/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=daniel
2025-06-09 16:52:40,516 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2025-06-09 16:52:40,516 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2025-06-09 16:52:40,516 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2025-06-09 16:52:40,516 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2025-06-09 16:52:40,517 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'sysinit.target', 'system.slice']
**After=['systemd-journald.socket', 'system.slice', '-.mount', 'network-online.target', 'basic.target', 'sysinit.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2025-06-09 16:52:40,517 [server.py:_initialize_component()] - Performing Component Post Init: [power]
2025-06-09 16:52:40,517 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2025-06-09 16:52:40,518 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2025-06-09 16:52:40,519 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 509, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable
2025-06-09 16:52:41,253 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2025-06-09 16:52:42,534 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'moonraker': [Errno -3] Temporary failure in name resolution
2025-06-09 16:52:44,472 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/daniel/printer_data/comms/moonraker.sock'
2025-06-09 16:52:44,472 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: basement
2025-06-09 16:52:44,473 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2025-06-09 16:52:44,550 [announcements.py:_fetch_moonlight()] - Failed to update subscription 'klipper': [Errno -3] Temporary failure in name resolution
2025-06-09 16:52:44,724 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-06-09 16:52:44,790 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'system.slice', 'sysinit.target']
**After=['sysinit.target', 'system.slice', 'network-online.target', '-.mount', 'systemd-journald.socket', 'basic.target']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/daniel/printer_data/systemd/klipper.env
**ExecStart=/home/daniel/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/daniel/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=daniel
2025-06-09 16:52:45,043 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-111-g4f00f219
2025-06-09 16:52:54,065 [base_deploy.py:log_info()] - PackageKit: Detected 145 package updates:
alsa-ucm-conf
apt
apt-utils
base-files
coreutils
cryptsetup
cryptsetup-bin
cryptsetup-initramfs
distro-info-data
dmidecode
dmsetup
dns-root-data
dpkg
dpkg-dev
e2fsprogs
firmware-sof-signed
fonts-noto-color-emoji
gir1.2-mutter-10
gir1.2-nm-1.0
gir1.2-packagekitglib-1.0
gjs
gnome-control-center
gnome-control-center-data
gnome-control-center-faces
gnome-remote-desktop
gnome-shell
gnome-shell-common
gnome-shell-extension-prefs
google-chrome-stable
grub-efi-amd64-bin
grub-efi-amd64-signed
initramfs-tools
initramfs-tools-bin
initramfs-tools-core
language-pack-en
language-pack-en-base
libapt-pkg6.0
libcom-err2
libcryptsetup12
libdevmapper1.02.1
libdpkg-perl
libegl-mesa0
libext2fs2
libgbm1
libgjs0g
libgl1-mesa-dri
libglapi-mesa
libglx-mesa0
libgpgme11
libgpgmepp6
libldap-2.5-0
libldap-common
libmalcontent-0-0
libmbim-glib4
libmbim-proxy
libmm-glib0
libmutter-10-0
libnautilus-extension1a
libnm0
libnss-systemd
libpackagekit-glib2-18
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpam0g
libpcap0.8
libpulse-mainloop-glib0
libpulse0
libpulsedsp
libpython3-dev
libpython3-stdlib
libseccomp2
libsmbclient
libsnmp-base
libsnmp40
libss2
libsystemd0
libudev1
libwbclient0
libxatracker2
linux-base
logsave
mesa-va-drivers
mesa-vdpau-drivers
mesa-vulkan-drivers
modemmanager
mutter
mutter-common
nautilus
nautilus-data
network-manager
network-manager-config-connectivity-ubuntu
openvpn
packagekit
packagekit-tools
pci.ids
plasma-distro-release-notifier
pulseaudio
pulseaudio-module-bluetooth
pulseaudio-module-gsettings
pulseaudio-utils
python-apt-common
python3
python3-apt
python3-dev
python3-distupgrade
python3-gpg
python3-minimal
python3-paramiko
python3-samba
python3-update-manager
samba-common
samba-common-bin
samba-dsdb-modules
samba-libs
shim-signed
smbclient
snapd
systemd
systemd-sysv
systemd-timesyncd
tcpdump
tracker-extract
tracker-miner-fs
ubuntu-advantage-tools
ubuntu-minimal
ubuntu-pro-client-l10n
ubuntu-release-upgrader-core
ubuntu-release-upgrader-gtk
ubuntu-release-upgrader-qt
ubuntu-standard
udev
update-manager
update-manager-core
update-notifier
update-notifier-common
xdg-desktop-portal
xdg-desktop-portal-gnome
xserver-common
xserver-xephyr
xserver-xorg-core
xserver-xorg-legacy
xwayland
ubuntu-pro-client
2025-06-09 16:52:54,491 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker status --porcelain -b) successfully finished
2025-06-09 16:52:54,496 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker branch --list --no-color) successfully finished
2025-06-09 16:52:54,501 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker remote get-url origin) successfully finished
2025-06-09 16:52:55,062 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/moonraker fetch origin --prune --progress) exited with return code 128
2025-06-09 16:52:55,065 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:52:55,567 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:52:55,567 [git_deploy.py:refresh_repo_state()] - Git Repo moonraker: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:55,567 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:55,847 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper status --porcelain -b) successfully finished
2025-06-09 16:52:55,853 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper branch --list --no-color) successfully finished
2025-06-09 16:52:55,859 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper remote get-url origin) successfully finished
2025-06-09 16:52:55,871 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper fetch origin --prune --progress) exited with return code 128
2025-06-09 16:52:55,874 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:52:56,375 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:52:56,375 [git_deploy.py:refresh_repo_state()] - Git Repo klipper: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:56,375 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:56,734 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config status --porcelain -b) successfully finished
2025-06-09 16:52:56,739 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config branch --list --no-color) successfully finished
2025-06-09 16:52:56,744 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config remote get-url origin) successfully finished
2025-06-09 16:52:56,756 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/mainsail-config fetch origin --prune --progress) exited with return code 128
2025-06-09 16:52:56,758 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:52:57,259 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:52:57,260 [git_deploy.py:refresh_repo_state()] - Git Repo mainsail-config: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:57,260 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:58,274 [base_deploy.py:log_info()] - Web Client mainsail: Github Request Error - [Errno -3] Temporary failure in name resolution
2025-06-09 16:52:58,274 [base_deploy.py:log_info()] - Web Client mainsail: Detected
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/daniel/mainsail
Local Version: v2.10.0
Remote Version: v2.10.0
Valid: True
Fallback Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.10.0/mainsail.zip
Download Size: 2081565
Content Type: application/zip
Rollback Version: v2.10.0
Rollback Repo: mainsail-crew/mainsail
2025-06-09 16:52:58,863 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging status --porcelain -b) successfully finished
2025-06-09 16:52:58,868 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging branch --list --no-color) successfully finished
2025-06-09 16:52:58,873 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging remote get-url origin) successfully finished
2025-06-09 16:52:58,883 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/Klipper-Adaptive-Meshing-Purging fetch origin --prune --progress) exited with return code 128
2025-06-09 16:52:58,886 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:52:59,387 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:52:59,387 [git_deploy.py:refresh_repo_state()] - Git Repo Klipper-Adaptive-Meshing-Purging: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:52:59,387 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:53:00,206 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup status --porcelain -b) successfully finished
2025-06-09 16:53:00,213 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup branch --list --no-color) successfully finished
2025-06-09 16:53:00,218 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup remote get-url origin) successfully finished
2025-06-09 16:53:00,228 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/klipper-backup fetch origin --prune --progress) exited with return code 128
2025-06-09 16:53:00,231 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:53:00,731 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:53:00,731 [git_deploy.py:refresh_repo_state()] - Git Repo klipper-backup: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:53:00,732 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:53:00,928 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest status --porcelain -b) successfully finished
2025-06-09 16:53:00,934 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest branch --list --no-color) successfully finished
2025-06-09 16:53:00,939 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest remote get-url origin) successfully finished
2025-06-09 16:53:00,950 [shell_command.py:_check_proc_success()] - Command (git -C /home/daniel/crowsnest fetch origin --prune --progress) exited with return code 128
2025-06-09 16:53:00,953 [shell_command.py:_check_proc_success()] - Command (find .git/objects/ -type f -empty | xargs rm) exited with return code 1
2025-06-09 16:53:01,454 [git_deploy.py:_repair_loose_objects()] - Attempt to repair loose objects failed, hard recovery is required
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1152, in _repair_loose_objects
    await shell_cmd.exec_cmd(
  File "/home/daniel/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'find .git/objects/ -type f -empty | xargs rm'
2025-06-09 16:53:01,454 [git_deploy.py:refresh_repo_state()] - Git Repo crowsnest: Initialization failure
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:53:01,455 [git_deploy.py:refresh()] - Error Refreshing git state
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 58, in refresh
    await self._update_repo_state()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 64, in _update_repo_state
    await self.repo.refresh_repo_state(need_fetch=need_fetch)
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 339, in refresh_repo_state
    await self.fetch()
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 748, in fetch
    await self._run_git_cmd_async(
  File "/home/daniel/moonraker/moonraker/components/update_manager/git_deploy.py", line 1217, in _run_git_cmd_async
    raise self.server.error(
moonraker.utils.ServerError: Unable to repair loose objects, use hard recovery
2025-06-09 16:54:01,374 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-06-09 16:54:01,374 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-06-09 16:54:01,624 [job_state.py:_handle_started()] - Job state initialized: standby
2025-06-09 16:54:01,882 [klippy_connection.py:_check_ready()] - Klippy ready
2025-06-09 16:54:02,377 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-06-09 16:54:35,602 [power.py:init_state()] - Device Init Error: printer_plug
Traceback (most recent call last):
  File "/home/daniel/moonraker/moonraker/components/power.py", line 898, in init_state
    state: int = await self._send_info_request()
  File "/home/daniel/moonraker/moonraker/components/power.py", line 884, in _send_info_request
    res = await self._send_tplink_command("info")
  File "/home/daniel/moonraker/moonraker/components/power.py", line 839, in _send_tplink_command
    reader, writer = await asyncio.open_connection(
  File "/usr/lib/python3.10/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.83', 9999)
2025-06-09 16:54:40,638 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.40
2025-06-09 16:54:40,639 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.40
2025-06-09 16:55:10,565 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2025-06-09 16:55:10,566 [application.py:log_request()] - 101 GET /websocket (127.0.0.1) [_TRUSTED_USER_] 1.50ms
2025-06-09 16:55:10,566 [websockets.py:open()] - Websocket Opened: ID: 140212930957888, Proxied: True, User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0, Host Name: localhost
2025-06-09 16:55:10,672 [websockets.py:_handle_identify()] - Websocket 140212930957888 Client Identified - Name: mainsail, Version: 2.10.0, Type: web
2025-06-09 16:55:20,798 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2025-06-09 16:55:22,053 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2025-06-09 16:55:24,103 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2025-06-09 16:55:24,104 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2025-06-09 16:55:24,353 [job_state.py:_handle_started()] - Job state initialized: standby
2025-06-09 16:55:24,610 [klippy_connection.py:_check_ready()] - Klippy ready
2025-06-09 16:55:25,107 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'extruder']
2025-06-09 17:26:02,841 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.165
2025-06-09 17:26:02,842 [application.py:log_request()] - 101 GET /websocket (192.168.0.165) [_TRUSTED_USER_] 1.27ms
2025-06-09 17:26:02,842 [websockets.py:open()] - Websocket Opened: ID: 140212921478608, Proxied: True, User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0, Host Name: 192.168.0.40
2025-06-09 17:26:02,848 [websockets.py:_handle_identify()] - Websocket 140212921478608 Client Identified - Name: mainsail, Version: 2.10.0, Type: web
2025-06-09 17:57:40,306 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 127.0.0.1
2025-06-09 18:27:40,312 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.0.165
